const keywords = [
    ".net",
    ".net developer",
    "3d modeling",
    "a/b email test",
    "a/b test",
    "a/b testing",
    "ab test",
    "ab testing",
    "abap",
    "abcl",
    "accessibility techniques",
    "actionscript",
    "active directory",
    "activemq",
    "ad technology",
    "ada",
    "adaptive autosar",
    "adas sw system",
    "adas/ad feature",
    "ado.net",
    "adobe aem",
    "adobe analytics",
    "adobe creative cloud",
    "adobe creative suite",
    "adobe illustrator",
    "adobe photoshop",
    "adobe powerbi",
    "adobe suite",
    "adobe xd",
    "adtech",
    "advanced analytics",
    "advanced analytics platforms",
    "advanced analytics solutions",
    "agile",
    "agile methodologies",
    "agile methods",
    "agile planning",
    "agile scrum team",
    "agile software development",
    "agile tools and processes",
    "agile work processes and tools",
    "agilescrum sprint events and cycles",
    "airflow",
    "aix",
    "ajax",
    "alf",
    "algol",
    "algolia",
    "algorithm design",
    "algorithm development",
    "algorithms",
    "alice",
    "alpine",
    "amazon web services",
    "amplitude",
    "analytical tools and techniques",
    "analytics",
    "analytics products",
    "anaplan",
    "android",
    "android developer",
    "angular",
    "angular.js",
    "angularjs",
    "animation",
    "ansible",
    "ansys",
    "anycast",
    "apache",
    "apache airflow",
    "apache camel",
    "apache druid",
    "apache flink",
    "apache kafka",
    "apache solr",
    "apache spark",
    "apex",
    "api",
    "api development",
    "api's",
    "apigee",
    "apl",
    "apollo",
    "app design",
    "app security",
    "applescript",
    "application code",
    "application developer",
    "application development",
    "application layer protocol",
    "application scaling",
    "application security engineer",
    "arcgis",
    "architecture",
    "arduino",
    "artificial intelligence",
    "ascii encoding",
    "asio",
    "asp",
    "asp.net",
    "aspice",
    "assembly",
    "assembly language",
    "asynchronous systems",
    "atlassian",
    "audio editing",
    "autoit",
    "automate reporting",
    "automated ci/cd",
    "automated testing",
    "automated tests",
    "automating asset inspections processes",
    "automation of processes",
    "automation solutions",
    "automation tools",
    "automotive adas",
    "automotive adas customer features",
    "automotive camera based adas",
    "automotive code",
    "autopilot",
    "autosar",
    "awk",
    "aws",
    "aws (amazon web services)",
    "aws kinesis",
    "aws redshift",
    "aws solutions architect",
    "azure",
    "azuredb",
    "b2b technology",
    "babel",
    "back end",
    "back-end",
    "back-end data display",
    "back-end framework",
    "back-end programming language",
    "backbone",
    "backbone.js",
    "backend",
    "balsamiq",
    "bash",
    "basic",
    "batch data",
    "batch data ingestion",
    "batch process",
    "bazel",
    "bbc basic",
    "bdd",
    "beam",
    "beanshell",
    "bgp",
    "big data technologies",
    "bigquery",
    "bing",
    "bing ads",
    "bioinformatics",
    "bitbucket",
    "blazor",
    "bliss",
    "blockchain",
    "blockchain developer",
    "bluetooth",
    "bootstrap",
    "browserify",
    "bsd",
    "btravis ci",
    "buffer",
    "bugzilla",
    "business analytics",
    "business intelligence",
    "business intelligence technologies",
    "business operation analytics",
    "c",
    "c#",
    "c# developer",
    "c++",
    "c/c++",
    "caching",
    "cad software",
    "cadence allegro",
    "cakephp",
    "cassandra",
    "catia",
    "cdn",
    "cecil",
    "celery",
    "centos",
    "cgi",
    "chart.js",
    "chemical engineering",
    "chromium",
    "chuck",
    "ci",
    "ci/cd",
    "cicd",
    "cifs and citrix",
    "cilk",
    "circleci",
    "cisco technologies",
    "citrix",
    "cli",
    "client satisfaction",
    "clist",
    "clojure",
    "cloud app adoption",
    "cloud computing",
    "cloud data services",
    "cloud infrastructure",
    "cloudformation",
    "cloudfront",
    "cloudsearch",
    "cloudwatch",
    "clustering",
    "cms",
    "cobol",
    "cobra",
    "cockroachdb",
    "cocoa",
    "code review",
    "codeigniter",
    "codepipeline",
    "codeship",
    "cognos",
    "color theory",
    "command line",
    "competitive analysis",
    "compiler",
    "component libraries",
    "component pascal",
    "computational analytics",
    "computational biology",
    "computer architecture",
    "computer engineer",
    "computer engineering",
    "computer programmer",
    "computer science",
    "computer security",
    "computer vision",
    "computer vision models",
    "concurrent pascal",
    "configuration management",
    "confluence",
    "connectivity technologies",
    "containerization",
    "content management",
    "content management system",
    "content management systems (cms)",
    "continuous deployment",
    "continuous improvement",
    "continuous integration",
    "continuous integration and deployment",
    "corba",
    "corel draw",
    "couchdb",
    "coupa",
    "cpq",
    "crazy egg",
    "create web pages",
    "crm",
    "crm pipeline",
    "cro (conversion rate optimization)",
    "cross functional",
    "cross functional collaboration",
    "cross-browser compatibility",
    "cross-functional",
    "cross-functional collaboration",
    "cross-functionally",
    "crypto",
    "cryptocurrency",
    "cryptography",
    "css",
    "css3",
    "csv",
    "cte",
    "cuda",
    "curl",
    "current web trends",
    "curry",
    "customer analytics",
    "customer engagement",
    "customer relationship management",
    "customer service",
    "customer success",
    "customer-facing marketing tools",
    "cypress",
    "cypress.io",
    "dal",
    "dap",
    "dart",
    "dash",
    "dashboard specifications",
    "dasl",
    "data analysis",
    "data analytics",
    "data and analysis",
    "data architecture",
    "data consolidation",
    "data driven",
    "data driven decisions",
    "data driven solutions",
    "data engineer",
    "data ingestion",
    "data lake",
    "data mining",
    "data modeling",
    "data models",
    "data pipeline",
    "data platform",
    "data presentation",
    "data processing",
    "data reporting",
    "data science",
    "data sets",
    "data sheets",
    "data solutions",
    "data storytelling",
    "data strategy",
    "data structure",
    "data structures",
    "data studio",
    "data validation exercises",
    "data visualization",
    "data visualization tools",
    "data warehouse",
    "data-driven",
    "data-driven analysis",
    "data-driven approach",
    "data-driven metrics",
    "data-informed techniques",
    "data-powered products",
    "database",
    "database administration",
    "database architecture",
    "database design",
    "databricks",
    "datadog",
    "dataflow",
    "dataflow/beam",
    "dataproc",
    "datorama",
    "dcf",
    "ddd",
    "dds",
    "debian",
    "debugger",
    "debugging",
    "decision trees",
    "deep learning",
    "delphi",
    "demand forecasting",
    "deployment",
    "descriptive / predictive models",
    "descriptive and predictive analytics",
    "descriptive models",
    "design",
    "design and implementation",
    "design code",
    "design experience",
    "design ideation",
    "design mockups",
    "design patterns",
    "design processes",
    "design software",
    "design specifications",
    "design studio",
    "design systems",
    "design thinking",
    "design tools",
    "designer",
    "desktop application development",
    "dev c++",
    "dev ops",
    "devexpress",
    "devise",
    "devops",
    "dh",
    "dhc",
    "dhcp",
    "dhoma",
    "digital advertising technology",
    "digital animation",
    "digital image processing",
    "digital marketing",
    "digital marketing tools",
    "digital simulation",
    "direct routing",
    "directory services",
    "dis",
    "discrete event simulation",
    "distributed computing",
    "distributed systems",
    "django",
    "docker",
    "document design",
    "document management system",
    "documentation",
    "documentation design",
    "documentation skills",
    "dom (document object model)",
    "domain driven design",
    "domain-driven design",
    "dotnetnuke",
    "dr",
    "dreamweaver",
    "driven execution",
    "driven methodology",
    "drones",
    "druid",
    "drupal",
    "dsc",
    "dsp",
    "dss",
    "dsssl",
    "dtrace",
    "dtos",
    "dynatrace",
    "dynamic advertising",
    "dynamic data sources",
    "dynamic programming",
    "e-commerce",
    "eclipse",
    "ecommerce",
    "ecommerce platform",
    "ecommerce platforms",
    "economics",
    "ecosystem",
    "edge computing",
    "editorial content",
    "edw",
    "edward",
    "ef",
    "effort to production quality code",
    "ejs",
    "elasticsearch",
    "elastiс",
    "electronic design",
    "elk stack",
    "embedded",
    "embedded c",
    "embedded systems",
    "emr",
    "enabler",
    "end user training",
    "end-to-end product",
    "endeca",
    "engineering",
    "enterprise architecture",
    "enterprise integration",
    "enterprise search",
    "entity framework",
    "entity framework core",
    "enzyme",
    "episerver",
    "erwin",
    "es5",
    "es6",
    "es7",
    "es8",
    "eslint",
    "ethereum",
    "etl",
    "etl tools",
    "ets",
    "excel",
    "excellence in analytics",
    "exchange server",
    "exos",
    "ext.js",
    "extensible data source",
    "extjs",
    "extract transform load",
    "eye for design",
    "f#",
    "f# programming language",
    "fabric.js",
    "facebook",
    "facebook ads",
    "facebook ads manager",
    "facebook pixel",
    "falcon",
    "fast-paced environment",
    "fast-paced technology environments",
    "fault tolerance",
    "feature enhancement",
    "feature implementation",
    "feature sets",
    "feathers",
    "firebase",
    "firebase analytics",
    "firestore",
    "fisheye",
    "fivetran",
    "flask",
    "flex",
    "flutter",
    "focus on quality",
    "fogbugz",
    "fontend",
    "foo",
    "forklift",
    "fortran",
    "fortress",
    "framework",
    "framework 7",
    "frameworks",
    "freertos",
    "front end",
    "front end developer",
    "front end frameworks",
    "front end web development",
    "front-end",
    "front-end code",
    "front-end development",
    "front-end engineer",
    "front-end framework",
    "front-end programming language",
    "front-end web development",
    "frontbase",
    "frontend",
    "full stack",
    "full stack developer",
    "full stack development",
    "full-stack",
    "full-stack developer",
    "functional programming",
    "functional testing",
    "fusion",
    "g suite",
    "g++",
    "gadfly",
    "gatling",
    "gdpr",
    "gearman",
    "geolocation",
    "geometric designs",
    "geospatial technology",
    "ggplot",
    "gis",
    "github",
    "gitlab",
    "gitlab-ci",
    "glassfish",
    "glee",
    "gluster",
    "glusterfs",
    "gnuplot",
    "go",
    "go js",
    "go-lang",
    "gocd",
    "godot",
    "google ads",
    "google adsense",
    "google adwords",
    "google analytics",
    "google app engine",
    "google bigquery",
    "google cloud",
    "google cloud platform",
    "google cloud storage",
    "google compute engine",
    "google data studio",
    "google drive",
    "google maps",
    "google search",
    "google search console",
    "google tag manager",
    "google webmaster tools",
    "gopher",
    "goreact",
    "gosec",
    "gosu",
    "graphql",
    "graphic design",
    "graphic design software",
    "graphics programming",
    "grep",
    "groovy",
    "group policy",
    "gson",
    "gulp",
    "gunicorn",
    "hadoop",
    "hadoop ecosystem",
    "haml",
    "handlebars.js",
    "hardening",
    "hardware",
    "hardware architecture",
    "hardware design",
    "harness",
    "haskell",
    "hazelcast",
    "hci",
    "heroku",
    "hexo",
    "hibernate",
    "high performance computing",
    "high-level languages",
    "highcharts",
    "hive",
    "homebrew",
    "honesty",
    "hotjar",
    "hp-ux",
    "hsqldb",
    "html",
    "html5",
    "http",
    "http/2",
    "http/3",
    "hubspot",
    "hudson",
    "humio",
    "hyperledger",
    "hyperv",
    "iaas",
    "ibm bluemix",
    "ibm db2",
    "ibm watson",
    "iconic",
    "ide",
    "ideation process",
    "ides",
    "ifttt",
    "illustrator",
    "image editing",
    "image processing",
    "imessage",
    "impala",
    "in-app marketing",
    "in-app messaging",
    "in-house tools",
    "incapsula",
    "incentivizing customer",
    "inclusion",
    "inclusive design",
    "inclusive technology",
    "incremental development",
    "incremental growth",
    "incubators",
    "indesign",
    "industrial design",
    "information architecture",
    "information security",
    "information technology",
    "information technology skills",
    "infra as code",
    "infrastructure",
    "infrastructure automation",
    "infrastructure as code",
    "infrastructure engineering",
    "infrastructure monitoring",
    "infusionsoft",
    "infragistics",
    "initiative",
    "innovation",
    "innovative solutions",
    "innovative thinking",
    "inotify",
    "input validation",
    "inserting relevant keywords",
    "insight",
    "instapage",
    "integration",
    "integration services",
    "integration testing",
    "intellectual property",
    "interaction design",
    "interactivity",
    "interface builder",
    "interface design",
    "interface design concepts",
    "interface design principles",
    "internal networking",
    "internal stakeholders",
    "internal tools",
    "internationalization",
    "internet protocols",
    "internet technology",
    "interop",
    "interpersonal skills",
    "intuition",
    "invision",
    "invision studio",
    "io.js",
    "ionic",
    "ios",
    "ios developer",
    "iot",
    "iot platforms",
    "ip",
    "iphone",
    "iphone development",
    "iso",
    "iso 9001",
    "it governance",
    "it infrastructure",
    "it security",
    "it service management",
    "itil",
    "itk",
    "ivr",
    "ixia",
    "j2ee",
    "jackson",
    "jade",
    "janus graph",
    "jasmine",
    "jasperreports",
    "java",
    "java ee",
    "java programming",
    "java se",
    "java/j2ee",
    "java8",
    "javaee",
    "javafx",
    "javascript",
    "javascript (es5)",
    "javascript (es6+)",
    "javascript developer",
    "javascript frameworks",
    "javascript libraries",
    "javascript programming language",
    "javaserver faces",
    "javaserver pages",
    "javaspring",
    "jax-rs",
    "jaxb",
    "jboss",
    "jdbc",
    "jekyll",
    "jenkins",
    "jest",
    "jetbrains",
    "jhipster",
    "jira",
    "jmeter",
    "jms",
    "job control language",
    "join tables",
    "joint applications",
    "jointjs",
    "joomla",
    "jpa",
    "jq",
    "jquery",
    "jquery mobile",
    "jquery ui",
    "js",
    "jsf",
    "json",
    "json api",
    "json schema",
    "json-ld",
    "jsonapi",
    "jsonp",
    "jstl",
    "julia",
    "julia language",
    "junit",
    "jupyter",
    "jupyter notebook",
    "jwt",
    "kafka",
    "kanban",
    "karma",
    "kdb",
    "kdb+",
    "kendo ui",
    "keras",
    "kerberos",
    "kernel",
    "kernel programming",
    "keystone",
    "kibana",
    "kinvey",
    "kivy",
    "kms",
    "knex.js",
    "knockout",
    "knockoutjs",
    "kong",
    "kops",
    "kotlin",
    "kotlin/native",
    "kubernetes",
    "kusto",
    "kvm",
    "labview",
    "lambda",
    "lambda expressions",
    "landscape design",
    "language skills",
    "languages",
    "laptop computers",
    "laravel",
    "large scale distributed systems",
    "large-scale data",
    "lastpass",
    "latex",
    "latte",
    "leadership",
    "leadership ability",
    "leadership development",
    "leadership experience",
    "leadership in energy and environmental design",
    "leadership skills",
    "lean",
    "lean development",
    "lean methodology",
    "lean product development",
    "lean six sigma",
    "learnability",
    "learning ability",
    "learning agility",
    "learning and development",
    "learning management systems",
    "learning new technologies",
    "legal",
    "less",
    "less (stylesheet language)",
    "leveldb",
    "lex",
    "libgdx",
    "libraries",
    "libreoffice",
    "lift",
    "lightroom",
    "lightsail",
    "lightswitch",
    "lighttpd",
    "linkedin",
    "linkedin ads",
    "linkedin marketing solutions",
    "linq",
    "linux",
    "linux administration",
    "linux command line",
    "linux kernel",
    "linux operating system",
    "linux servers",
    "linux/unix",
    "liquid",
    "lis",
    "lisp",
    "lithium",
    "litmus",
    "litmus test",
    "live chat",
    "llc",
    "llp",
    "llvm",
    "load balancing",
    "load testing",
    "log analysis",
    "log management",
    "log4j",
    "logging",
    "logstash",
    "looker",
    "lookup",
    "loopback",
    "lsof",
    "lua",
    "lucene",
    "lxd",
    "lynis",
    "lynx",
    "lyris",
    "mac os",
    "mac os x",
    "macbook",
    "machine learning",
    "machine learning algorithms",
    "machine learning libraries",
    "machine learning models",
    "machine learning pipelines",
    "machine learning platforms",
    "machine learning techniques",
    "machine learning tools",
    "machine vision",
    "macos",
    "magento",
    "mailchimp",
    "mailgun",
    "mailtrap",
    "maintainable code",
    "maintaining databases",
    "make",
    "makefile",
    "making decisions",
    "malware analysis",
    "management",
    "management skills",
    "managing",
    "managing projects",
    "manipulating data",
    "manning",
    "manual testing",
    "manufacturing",
    "map/reduce",
    "mapkit",
    "mapreduce",
    "mariadb",
    "marionette.js",
    "marketing",
    "marketing analytics",
    "marketing automation",
    "marketing automation tools",
    "marketing campaigns",
    "marketing platforms",
    "marketing strategy",
    "marketo",
    "markup languages",
    "marvel",
    "masm",
    "mason",
    "massively parallel processing",
    "master pages",
    "material design",
    "materialize",
    "matlab",
    "maven",
    "maya",
    "mbaas",
    "mcse",
    "mda",
    "mdm",
    "mdx",
    "me",
    "mean stack",
    "mean.js",
    "measurements",
    "measuring instruments",
    "mechanical design",
    "medialoot",
    "media queries",
    "medical imaging",
    "memcache",
    "memcached",
    "mercurial",
    "mesos",
    "message queues",
    "messaging",
    "messaging api",
    "messaging apps",
    "meta-programming",
    "metadata",
    "metaprogramming",
    "meteor",
    "metrics",
    "mfc",
    "microcontrollers",
    "microfrontends",
    "microservices",
    "microservices architecture",
    "microsoft .net",
    "microsoft access",
    "microsoft active directory",
    "microsoft ad",
    "microsoft azure",
    "microsoft azure cloud services",
    "microsoft bi",
    "microsoft dynamics",
    "microsoft dynamics crm",
    "microsoft excel",
    "microsoft exchange",
    "microsoft iis",
    "microsoft office",
    "microsoft office 365",
    "microsoft office suite",
    "microsoft power bi",
    "microsoft project",
    "microsoft sharepoint",
    "microsoft sql server",
    "microsoft technologies",
    "microsoft visual studio",
    "microsoft windows",
    "microsoft word",
    "middleman",
    "middleware",
    "migration",
    "mikrotik",
    "miller",
    "millwright",
    "mind mapping",
    "mindset",
    "mingw",
    "minikube",
    "mining",
    "mirc",
    "mirth",
    "mirth connect",
    "miva",
    "mjml",
    "mkl",
    "ml",
    "ml model deployment",
    "mlflow",
    "mmix",
    "mmixware",
    "mobile",
    "mobile analytics",
    "mobile app development",
    "mobile application",
    "mobile application development",
    "mobile applications",
    "mobile architecture",
    "mobile automation",
    "mobile computing",
    "mobile design",
    "mobile device management",
    "mobile devices",
    "mobile development",
    "mobile first",
    "mobile first design",
    "mobile marketing",
    "mobile security",
    "mobile testing",
    "mobile ui",
    "mobile ui design",
    "mobile ux",
    "mobile web",
    "mobile web design",
    "mobile-first",
    "mockups",
    "mod_perl",
    "model driven architecture",
    "model-view-controller",
    "modeling",
    "modeling languages",
    "modelling",
    "modular programming",
    "modularity",
    "module",
    "module development",
    "mongodb",
    "mongoose",
    "monitoring",
    "monitoring and evaluation",
    "monitoring tools",
    "monitorenterprise",
    "moo",
    "moodle",
    "mootools",
    "mopub",
    "morale",
    "morph",
    "moss",
    "motivation",
    "motorola",
    "movidius",
    "mpi",
    "mq",
    "mq series",
    "mql4",
    "mqtt",
    "ms access",
    "ms dos",
    "ms office",
    "ms office tools",
    "ms project",
    "ms sql",
    "ms sql server",
    "ms-dos",
    "msbuild",
    "msc",
    "msmq",
    "mssql",
    "mt",
    "multithreading",
    "mura cms",
    "murex",
    "mvc",
    "mvc architecture",
    "mvc framework",
    "mvp",
    "mvvm",
    "mvvm architecture",
    "mvvm pattern",
    "mx",
    "myob",
    "mysql",
    "nagios",
    "nanotechnology",
    "nashorn",
    "nasm",
    "native advertising",
    "native ios/android apps",
    "native libraries",
    "native modules",
    "nativescript",
    "natural language processing",
    "navigation",
    "ncr",
    "neat",
    "nebula",
    "neo4j",
    "neon",
    "netapp",
    "netbeans",
    "netbsd",
    "netflix",
    "netlify",
    "netops",
    "network",
    "network administration",
    "network architecture",
    "network design",
    "network engineering",
    "network monitoring",
    "network protocols",
    "network security",
    "network topologies",
    "networking",
    "neural networks",
    "new features",
    "new relic",
    "new systems",
    "next.js",
    "nginx",
    "nhibernate",
    "nim",
    "nimble",
    "nintex",
    "nix",
    "nixos",
    "nlb",
    "nlp",
    "nlp models",
    "nmap",
    "nock",
    "node.js",
    "nodejs",
    "nodejs developer",
    "nosql",
    "nosql databases",
    "nova",
    "npm",
    "nrf52832",
    "nsx",
    "ntfs",
    "ntp",
    "nunit",
    "nuxt.js",
    "nvidia",
    "nx-os",
    "oauth",
    "oauth 2.0",
    "object detection models",
    "object oriented programming",
    "object-c",
    "object-oriented design",
    "object-oriented programming",
    "objective-c",
    "observable",
    "ocaml",
    "oci",
    "octave",
    "odbc",
    "office 365",
    "offline storage",
    "oledb",
    "oltp",
    "omni-channel marketing",
    "omnichannel",
    "on-page seo",
    "online advertising",
    "online analytics",
    "online marketing",
    "online marketing tools",
    "ontology",
    "opencv",
    "openflow",
    "opengl",
    "opengl es",
    "openid",
    "openindiana",
    "openjdk",
    "openmp",
    "openstack",
    "openvpn",
    "operational excellence",
    "operations",
    "operations research",
    "operations tools",
    "operator",
    "opsgenie",
    "optimization",
    "optimizely",
    "oracle",
    "oracle adf",
    "oracle apex",
    "oracle bi",
    "oracle dba",
    "oracle ebs",
    "oracle forms",
    "oracle pl/sql",
    "oracle r12",
    "oracle soa",
    "orchard cms",
    "orchestration",
    "oreilly",
    "organization",
    "organizational skills",
    "osgi",
    "osx",
    "outbound marketing",
    "outlook",
    "outlook express",
    "outsourcing",
    "owa",
    "owasp",
    "owl",
    "owsap",
    "p5.js",
    "p6",
    "paas",
    "pachyderm",
    "packer",
    "packrat",
    "pact",
    "pandas",
    "paper.js",
    "parallel processing",
    "parallel programming",
    "parallelism",
    "parasoft",
    "parsley",
    "parse",
    "parsing",
    "pascal",
    "passion",
    "passport.js",
    "password manager",
    "patents",
    "path analysis",
    "paxos",
    "pbi",
    "pbrt",
    "pci",
    "pcl",
    "pcre",
    "pdca",
    "pdf",
    "pdfkit",
    "pdl",
    "penetration testing",
    "pentaho",
    "performance analysis",
    "performance engineering",
    "performance optimization",
    "performance testing",
    "perforce",
    "perl",
    "perl programming",
    "perl scripting",
    "perl6",
    "persistent storage",
    "personalization",
    "personas",
    "pfsense",
    "pgp",
    "phalcon",
    "phantomjs",
    "phoenix",
    "phonegap",
    "photoshop",
    "php",
    "php 5",
    "php 7",
    "php developer",
    "php framework",
    "php unit",
    "phpunit",
    "physical layer protocol",
    "pick",
    "pico",
    "pig",
    "pil",
    "pilot",
    "ping",
    "pingdom",
    "pip",
    "pipeline",
    "pipenv",
    "pipewire",
    "pjax",
    "pl",
    "pl/sql",
    "plc",
    "pld",
    "plex",
    "ploi",
    "plone",
    "plotly",
    "plsql",
    "pmi",
    "pmp",
    "pmp certification",
    "pocket",
    "podcast advertising",
    "pods",
    "point of sale",
    "point-of-sale (pos)",
    "polymer",
    "poo",
    "portfolio management",
    "posix",
    "postcss",
    "postgresql",
    "postman",
    "postmark",
    "postscript",
    "powershell",
    "ppc",
    "ppc advertising",
    "ppc campaign management",
    "ppc marketing",
    "pprof",
    "pr",
    "practical extraction and reporting language",
    "preact",
    "predictive analytics",
    "predictive maintenance",
    "predictive modeling",
    "prefork",
    "prelude",
    "premier",
    "premium",
    "prestashop",
    "preventative maintenance",
    "primavera",
    "primefaces",
    "principal",
    "privacy",
    "privacy compliance",
    "privacy laws",
    "private cloud",
    "private cloud environments",
    "private clouds",
    "private label",
    "private networks",
    "problem solving",
    "problem-solving",
    "problem-solving ability",
    "problem-solving skills",
    "proc",
    "process",
    "process automation",
    "process control",
    "process engineering",
    "process improvement",
    "process improvements",
    "process management",
    "process modeling",
    "process optimization",
    "process oriented",
    "processing",
    "processing.js",
    "procurement",
    "product analytics",
    "product design",
    "product development",
    "product enhancement",
    "product innovations",
    "product life cycle",
    "product life cycle management",
    "product management",
    "product manager",
    "product marketing",
    "product marketing manager",
    "product owner",
    "production",
    "production environment",
    "production level code",
    "production monitoring",
    "production processes",
    "production systems",
    "production-level code",
    "productivity tools",
    "products",
    "profiling",
    "program manager",
    "programmatic advertising",
    "programming",
    "programming language",
    "programming languages",
    "programming skills",
    "project coordination",
    "project design",
    "project lifecycle",
    "project management",
    "project management skills",
    "project management tools",
    "project manager",
    "project plans",
    "project portfolio",
    "project portfolio management",
    "project scope",
    "project tracking",
    "prometheus",
    "properties",
    "prospecting",
    "prototyping",
    "proxy",
    "puppet",
    "purescript",
    "purescript programming language",
    "push notification",
    "push notifications",
    "pwa",
    "pwas",
    "pxe",
    "pycharm",
    "pyjs",
    "pymongo",
    "pymssql",
    "pyodbc",
    "pyramid",
    "pyramid analytics",
    "pyrex",
    "pytest",
    "python",
    "python 3",
    "python developer",
    "python programming",
    "python scripting",
    "python/django",
    "pytorch",
    "q",
    "r&d",
    "rabbit mq",
    "rabbitmq",
    "radio access networks",
    "rails",
    "rapid prototyping",
    "rapidweaver",
    "raspberry pi",
    "ravendb",
    "rds",
    "react",
    "react developer",
    "react js",
    "react native",
    "react.js",
    "reactjs",
    "reactnative",
    "real time",
    "real-time",
    "real-time analysis",
    "real-time systems",
    "realm mobile database",
    "realtime",
    "rebol",
    "redis",
    "redshift",
    "redux",
    "regex",
    "relational database",
    "release criteria and management",
    "release infrastructure",
    "release management",
    "reliability",
    "report automation",
    "requirements analysis",
    "requirements gathering",
    "research and development",
    "resolve dependencies",
    "responsive",
    "responsive application",
    "responsive design",
    "responsive development",
    "rest",
    "rest apis",
    "rest applications",
    "restapi",
    "restful",
    "restful api",
    "restful services",
    "restlet",
    "rfp process",
    "rhel",
    "risk management",
    "risk mitigation",
    "roadmap",
    "roadmap planning",
    "roadmap strategy",
    "roadmunk",
    "robotics",
    "robotics engineer",
    "robots",
    "role-based access",
    "root cause analysis",
    "ros",
    "routing",
    "routing protocol",
    "rpg",
    "rspec",
    "ruby",
    "ruby on rails",
    "rust",
    "rxjava",
    "s-lang",
    "s-plus",
    "s3",
    "saas",
    "saas (software as a service)",
    "saas attribution modeling",
    "saas models outcome-based models",
    "saas product",
    "salesforce app exchange",
    "salesforce crm",
    "salesforce developer",
    "saml",
    "saml integrations",
    "sap",
    "sas",
    "sas macros",
    "sas stat",
    "sass",
    "sass/less",
    "scada",
    "scala",
    "scalability",
    "scalable",
    "scalable processes",
    "schema",
    "scientific computing",
    "scikit learn",
    "scikit-learn",
    "scikitlearn",
    "scipy",
    "scripting",
    "scrum",
    "scrum ceremonies",
    "scrum master",
    "scrum methodologies",
    "scrum processes",
    "scss",
    "sdk",
    "sdlc",
    "search engine marketing",
    "search engine optimization",
    "security",
    "security compliance",
    "sed",
    "segment",
    "segmentation",
    "selenium",
    "semantic ui",
    "sem",
    "sensor calibration",
    "sentry",
    "seo",
    "seo optimization",
    "sequential and multi-armed bandit",
    "server administration",
    "server-side scripting",
    "serverless",
    "service level agreements",
    "service production marketing technology",
    "sftp",
    "sgml",
    "sharepoint",
    "sharepoint developer",
    "shell",
    "shell script",
    "shell scripting",
    "signal processing",
    "simula",
    "simulink",
    "sip",
    "site reliability",
    "six sigma",
    "sketch",
    "sklearn",
    "sla",
    "slack",
    "slo",
    "smalltalk",
    "smartly",
    "smil",
    "snmp",
    "snobol",
    "snowflake",
    "sns",
    "soap",
    "social & mobile applications",
    "software + hardware",
    "software architecture",
    "software developer",
    "software development",
    "software development life cycle",
    "software development lifecycle",
    "software development roadmap",
    "software engineer",
    "software engineering",
    "software security",
    "software stacks",
    "software testing",
    "software workflow",
    "software-defined networking",
    "solaris/aix",
    "solidity",
    "solr",
    "source / version control",
    "source code",
    "spam",
    "spark",
    "specification development",
    "specs",
    "spin",
    "spl2",
    "splunk",
    "spring",
    "spring boot",
    "spring cloud",
    "spring data",
    "spring framework",
    "spring mvc",
    "sprint planning",
    "spss",
    "sql",
    "sql developer",
    "sql querying",
    "sql server",
    "sql-like scripting language",
    "sqlalchemy",
    "sqlite",
    "sqs",
    "squirrel scripting",
    "sre",
    "ssh",
    "ssi",
    "ssl",
    "sso",
    "stack overflow",
    "stakeholder management",
    "standard business processes",
    "standard practices",
    "start-ups",
    "startup",
    "stata",
    "state management",
    "statistical methodologies",
    "statistical methods",
    "statistical modeling",
    "statistical packages",
    "statistics",
    "storage solutions",
    "storage systems and management",
    "storybook",
    "stream data",
    "streaming",
    "structural engineering",
    "structural layouts",
    "subversion",
    "success metrics",
    "suitescript",
    "supervised",
    "supervised learning",
    "svn",
    "swagger",
    "swift",
    "switching",
    "symfony",
    "syslog",
    "system integration",
    "systemc",
    "systems analysis",
    "tableau",
    "task automation",
    "tcl",
    "tcl/tk",
    "tcp",
    "tcp/ip",
    "tdd",
    "tech stack",
    "technical architecture",
    "technical documentation",
    "technical product management",
    "technical reporting",
    "technical support",
    "technology trends and architectures",
    "telecommunications",
    "tensorflow",
    "teradata",
    "terraform",
    "test & quality",
    "test automation",
    "test development",
    "test driven development",
    "test infrastructure",
    "test plan",
    "test planning",
    "test strategies",
    "test-driven development",
    "test-driven-development",
    "testing",
    "tex and latex",
    "tik tok",
    "tiktok",
    "tls",
    "tms",
    "tomcat",
    "tooling development",
    "tornado",
    "tqm (total quality management)",
    "transactional law",
    "transactions",
    "travis",
    "travis ci",
    "travisci",
    "trello",
    "troubleshooting",
    "troubleshooting/debugging",
    "tsql",
    "tuning",
    "tunneling",
    "turing",
    "twilio",
    "twitter",
    "twitter ads",
    "tws",
    "type script",
    "typescript",
    "typography",
    "uat",
    "ubuntu",
    "udp",
    "ui",
    "ui design",
    "ui design and development",
    "ui developer",
    "ui engineering",
    "ui standards",
    "ui toolkits and frameworks",
    "ui/ux",
    "umbraco",
    "uml (unified modeling language)",
    "unbounce",
    "unified modeling language",
    "unit and integration testing",
    "unit test",
    "unity developer",
    "unix",
    "unix programming",
    "unix shell",
    "unsupervised",
    "unsupervised learning",
    "uptime",
    "url",
    "usability",
    "use cases",
    "user centric",
    "user design",
    "user experience",
    "user features",
    "user feedback",
    "user interface",
    "user interface design",
    "user requirements",
    "user research",
    "user scenarios",
    "user stories",
    "user story writing",
    "user test",
    "user testing plans",
    "user testing sessions",
    "user-centered design",
    "user-centered design techniques",
    "user-centric",
    "ux",
    "ux design",
    "ux design methodologies",
    "ux design principles",
    "ux design processes",
    "ux patterns",
    "ux research",
    "ux research methods",
    "ux/design language style libraries",
    "ux/ui",
    "validate",
    "validation",
    "vanilla js",
    "vbscript",
    "vercel",
    "verilog",
    "version control",
    "version control system",
    "version repository",
    "vertica",
    "vertx",
    "vhdl",
    "vi",
    "video editing",
    "vim",
    "vim/vi",
    "virtualization",
    "visual basic",
    "visual design",
    "visual foxpro",
    "visual studio",
    "visualforce",
    "visualization software",
    "vlan",
    "vmware",
    "voip",
    "vpn",
    "vrfs",
    "vrml",
    "vrrp",
    "vue",
    "vue.js",
    "vuejs",
    "wap",
    "wap/wml",
    "wcag",
    "wcag 2.1 compliance standards",
    "wcf",
    "weave flux",
    "web",
    "web accessibility",
    "web api",
    "web app",
    "web application",
    "web application development",
    "web applications",
    "web architecture",
    "web based software applications",
    "web design",
    "web developer",
    "web development",
    "web hosting",
    "web infrastructure",
    "web performance",
    "web production",
    "web projects",
    "web rollout",
    "web security",
    "web services",
    "web site",
    "web standards",
    "web technologies",
    "web technology",
    "web3",
    "webdriverio",
    "webkit",
    "webpack",
    "webrtc",
    "website application",
    "website development",
    "website hosting",
    "website infrastructure",
    "websockets",
    "windows powershell",
    "wire frame",
    "wireframe",
    "wireframes",
    "wireframing",
    "wml",
    "wms",
    "wordpress",
    "wordpress developer",
    "wpf",
    "wsdl",
    "wsgi",
    "xamarin",
    "xaml",
    "xhtml",
    "xl deploy",
    "xml",
    "xotcl",
    "xpath",
    "xsl",
    "xslt",
    "yaml",
    "yarn",
    "yui",
    "zapier",
    "zend framework",
    "zendesk",
    "zeromq",
    "zikula",
    "zuora"
  ];
  
  

const exampleDataLever = {
    name: 'Fo Lina',
    pronouns: 'He/him',
    email: 'fo.lina@usefolio.ai',
    phone: '123-456-7890',
    currentCompany: 'ABC Corp',
    linkedInURL: 'https://www.linkedin.com/in/folina/',
    gitHubURL: 'https://github.com/folina',
    portfolioURL: 'https://www.folinafofina.com',
    country: 'United States [USA]', // The country value should match the exact text of one of the option elements
    languages: ['English (ENG)', 'Spanish (SPA)'], // The language values should match the exact values of the checkbox elements
    preferredName: 'Fo',
    namePronunciation: 'pho lie nuh'
};

const exampleDataGreenhouse = {
    firstName: 'Fo',
    lastName: 'Lina',
    email: 'fo.linna@usefolio.ai',
    phone: '123-456-7890',
    devField1: 'Developer field value'
};

function parseSentencesFromHTML(html) {
    // Use DOMParser to convert the HTML string into a document object.
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');

    let rawTexts = [];

    // Traverse the document and extract text content from block-level elements.
    doc.body.querySelectorAll('p, li, div, h1, h2, h3, h4, h5, h6').forEach(elem => {
        let text = elem.textContent.trim();
        if (text) {
            rawTexts.push(text);
        }
    });

    // Combine all extracted texts and split into sentences.
    const combinedText = rawTexts.join(' • ');
    return parseSentencesFromText(combinedText);
}

function parseSentencesFromText(text) {
    // Split the text by '•' first to treat each list item as a separate sentence
    let potentialSentences = text.split('•').map(s => s.trim()).filter(Boolean);

    let sentences = [];

    // Regular expression pattern for sentence boundaries
    const pattern = /[^.!?]+[.!?]*/g;

    // Parse each potential sentence further to identify actual sentence boundaries
    potentialSentences.forEach(potentialSentence => {
        const matches = potentialSentence.match(pattern);
        if (matches) {
            // For each match, remove the dot and push to sentences
            matches.forEach(match => {
                sentences.push(match.replace('•', '').trim());
            });
        }
    });

    return sentences;
}


function escapeRegExp(string) {
    return string.replace(/[.*+\-?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}


function filterSentences(keywords, sentences) {
    return sentences.filter(sentence => {
        const sentenceLowered = sentence.toLowerCase();
        return keywords.some(keyword => {
            const escapedKeyword = escapeRegExp(keyword.toLowerCase());
            const regex = new RegExp('\\b' + escapedKeyword + '(\\b)');
            return regex.test(sentenceLowered);
        });
    });
}

// Function to fill the forms
function greenhouseFill(data) {
    // Fill out the text fields
    const firstNameField = document.getElementById('first_name');
    const lastNameField = document.getElementById('last_name');
    const emailField = document.getElementById('email');
    const phoneField = document.getElementById('phone');

    if (firstNameField) firstNameField.value = data.firstName || '';
    if (lastNameField) lastNameField.value = data.lastName || '';
    if (emailField) emailField.value = data.email || '';
    if (phoneField) phoneField.value = data.phone || '';
    
    // You may also handle the file upload section if needed
    // It depends on how the website handles file uploads
    // Generally, you need to trigger a file picker dialog or drag and drop interface
    const eduSection = document.querySelector("#education_section input")
    if (eduSection) {
        document.querySelector("#education_section input").value = "Stanford University";
        var event = new Event('change');
        eduSection.dispatchEvent(event);
    }
}
function leverFill(data) {
    const form = document.getElementById('application-form');
    
    if (form) {
        // Fill the full name
        const nameInput = form.querySelector('input[name="name"]');
        if (nameInput) {
            nameInput.value = data.name;
        }

        // Check the pronouns
        const pronounsInput = form.querySelector(`input[name="pronouns"][value="${data.pronouns}"]`);
        if (pronounsInput) {
            pronounsInput.checked = true;
        }

        // Fill the email
        const emailInput = form.querySelector('input[name="email"]');
        if (emailInput) {
            emailInput.value = data.email;
        }

        // Fill the phone number
        const phoneInput = form.querySelector('input[name="phone"]');
        if (phoneInput) {
            phoneInput.value = data.phone;
        }

        // Fill the current company
        const companyInput = form.querySelector('input[name="org"]');
        if (companyInput) {
            companyInput.value = data.currentCompany;
        }

        // Fill the LinkedIn URL
        const linkedInInput = form.querySelector('input[name="urls[LinkedIn]"]');
        if (linkedInInput) {
            linkedInInput.value = data.linkedInURL;
        }

        // Fill the GitHub URL
        const gitHubInput = form.querySelector('input[name="urls[GitHub]"]');
        if (gitHubInput) {
            gitHubInput.value = data.gitHubURL;
        }

        // Fill the Portfolio URL
        const portfolioInput = form.querySelector('input[name="urls[Portfolio]"]');
        if (portfolioInput) {
            portfolioInput.value = data.portfolioURL;
        }

        const countrySelect = form.querySelector('select[name^="cards"][name$="[field0]"]');
        if (countrySelect) {
            countrySelect.value = Array.from(countrySelect.options)
                .find(option => option.text.trim() === data.country)?.value || "";
            const event = new Event('change');
            countrySelect.dispatchEvent(event);  // Trigger a change event to update the UI
        }
        
        // Check the language skills
        const languages = data.languages || [];
        languages.forEach(language => {
            const languageCheckbox = form.querySelector(`input[name^="cards"][name$="[field1]"][value="${language}"]`);
            if (languageCheckbox) {
                languageCheckbox.checked = true;
            }
        });

    } else {
        console.error('Application form not found');
    }
}


const handlers = {
    'lever.co': () => {
        const currentUrl = window.location.href;
        const targetUrl = currentUrl.replace('/apply', '');


        // Fetch the HTML content of the target page without navigating away from the current page
        fetch(targetUrl)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok ' + response.statusText);
                }
                return response.text();  // Parse the text from the response
            })
            .then(html => {
                // Create a new HTML document from the response
                const parser = new DOMParser();
                const doc = parser.parseFromString(html, 'text/html');

                // Now you can query the doc object as you would the current document
                const metaTag = doc.querySelector('meta[property="og:description"]');
                const scriptTag = doc.querySelector('script[type="application/ld+json"]');
                if (scriptTag) {
                    try {
                        const jsonData = JSON.parse(scriptTag.textContent);
                        if (jsonData.description) {
                            const html = jsonData.description;
                            // // Step 1: Remove all HTML tags and add a space to avoid merging words
                            // const text = html.replace(/<\/?[^>]+(>|$)/g, " ");

                            // // Step 2: Split text into sentences
                            // // This regex looks for sentence-ending punctuation (., !, ?) followed by spaces
                            // const sentences = text.match(/[^.!?]+[.!?]+/g);
                            sentences = parseSentencesFromHTML(html)
                            console.log(
                                filterSentences(
                                    keywords,
                                    sentences
                                )
                            )
                        } else {
                            console.log("The 'description' field is not found in the JSON data.");
                        }
                    } catch (error) {
                        console.error("Error parsing the JSON content.", error);
                    }
                } else if (metaTag) {
                    console.log(metaTag.getAttribute('content'));
                    console.warn("Got response from website");
                } else {
                    console.log('Neither the job description div nor the meta tag was found on lever.co.');
                }
            })
            .catch(error => {
                console.error('There has been a problem with your fetch operation:', error);
            }
        );

        leverFill(exampleDataLever);
    
    },
    'myworkdayjobs.com': () => {
        const metaTag = document.querySelector('meta[property="og:description"]');
        
        if (metaTag) {
            sentences = parseSentencesFromText(metaTag.getAttribute('content'));
            console.log(
                filterSentences(
                    keywords,
                    sentences
                )
            )
        } else {
            console.log('The meta tag with property "og:description" is not found on myworkdayjobs.com.');
        }
    },
    'greenhouse.io': () => {
        
        const scriptTag = document.querySelector('script[type="application/ld+json"]');
        if (scriptTag) {
            try {
                const jsonData = JSON.parse(scriptTag.textContent);
                if (jsonData.description) {
                    const html = jsonData.description;
                    sentences = parseSentencesFromHTML(html)
                            console.log(
                                filterSentences(
                                    keywords,
                                    sentences
                                )
                            )
                } else {
                    console.log("The 'description' field is not found in the JSON data.");
                }
            } catch (error) {
                console.error("Error parsing the JSON content.", error);
            }
        } else {
            console.log("The script tag of type 'application/ld+json' is not found.");
        }

        greenhouseFill(exampleDataGreenhouse);
    }
};

const currentHostname = window.location.hostname;

Object.keys(handlers).forEach((key) => {
    if (currentHostname.includes(key)) {
        handlers[key]();
    }
});

